name: B4 Matrix

on:
  workflow_dispatch:

jobs:
  get-batches:
    runs-on: ubuntu-latest
    outputs:
      batch_list: ${{ steps.fetch.outputs.batch_list }}
    steps:
      - name: Fetch
        id: fetch
        run: |
          BATCH_LIST=$(seq 0 9 | jq -c -s '.')
          echo "batch_list=$BATCH_LIST" >> $GITHUB_OUTPUT

  backup:
    needs: get-batches
    runs-on: ubuntu-latest
    strategy:
      matrix:
        batch: ${{ fromJSON(needs.get-batches.outputs.batch_list) }}
      fail-fast: false
    steps:
      - run: echo "b4 matrix batch ${{ matrix.batch }} ok"
